### PR TITLE
feat: add substrait mappings for bitwise ops

### PR DESCRIPTION
**Pull request by richtia**
Add ibis -> substrait op mappings for bitwise ops

### CODE REVIEW

**Comment by gforsyth** [comment]
thanks, @richtia !  I've put in #522 to fix the CI issues -- once that's merged in if you want to rebase and squash, this should be good to go in.

**Comment by gforsyth** [comment]
Ok, CI is green on `main`, so you should be good to update

**Comment by richtia** [comment]
> Ok, CI is green on `main`, so you should be good to update

Updated!  Looks like i'm getting 1 failure still though.

**Comment by gforsyth** [comment]
thanks, @richtia !

**Pull request merged**
