### PR TITLE
Add comments to test_pyarrow::test_extension_udf

### PR DESCRIPTION
**Pull request by anjakefala**

### CODE REVIEW

**Review by gforsyth — CHANGES_REQUESTED** [review]
Thanks for putting this together @anjakefala!

One small nit on one of the comments, but this is a big improvement!

**Comment by anjakefala** [comment]
Hi! 

I am sorry it took so long, I was AFK for a week. Keeping an eye on how the build goes. =)

**Comment by gforsyth** [comment]
> I am sorry it took so long, I was AFK for a week. Keeping an eye on how the build goes. =)

No problem!  Time away is good.

**Review by gforsyth — APPROVED** [review]
Just had to run `black` on `test_pyarrow.py`, but this is good to go.  Thanks @anjakefala !

**Pull request merged**
