### PR TITLE
fix: cast floor and ceil to integer types to workaround acero

### LINKED ISSUE #410: `Ceil` and `Floor` returns floating type when executing with Acero
I observed that when I execute `ceil` and `floor` with Acero backend, it returns a double column where in ibis this is an integer column.

To make this consistent, perhaps we should add a cast operator when translating ibis to substrait?

### PR DESCRIPTION
**Pull request by gforsyth**
Acero's return type for floor and ceil is float64, so we cast
to ensure that the return type of the data matches the ibis expression
type.

Fixes #410.

### CODE REVIEW

**Comment by cpcloud** [comment]
cc @icexelloss this should be the last of the hot fixes for acero integration

**Comment by amoeba** [comment]
I just tested this locally and am getting an error. My steps were:

1. Generate a Substrait plan for a query like `t.mutate(a=t["a"].floor())` and serialize as JSON from ibis-substrait
2. Consume that plan via `pa.substrait.run_query()`

```
Failed query query-0.json with exception: conversion to arrow::compute::Expression from Substrait expression cast {
  type {
    i64 {
      nullability: NULLABILITY_NULLABLE
    }
  }
  input {
    scalar_function {
      function_reference: 1
      output_type {
        i64 {
          nullability: NULLABILITY_NULLABLE
        }
      }
      arguments {
        value {
          selection {
            direct_reference {
              struct_field {
              }
            }
            root_reference {
            }
          }
        }
      }
    }
  }
}

/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:382  FromProto(expr, ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/serde.cc:173  FromProto(plan_rel.has_root() ? plan_rel.root().input() : plan_rel.rel(), ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/util.cc:35  engine::DeserializePlans(substrait_buffer, registry, nullptr, conversion_options)
```

**Comment by cpcloud** [comment]
cc @westonpace Should this work?

**Comment by amoeba** [comment]
This does not currently working and is blocked by https://issues.apache.org/jira/browse/ARROW-16550.

**Comment by snadukudy** [comment]
Hello, I just wanted to update that this PR is no longer blocked and https://github.com/apache/arrow/pull/34050 has merged now to resolve Arrow GH issue https://github.com/apache/arrow/issues/31910 
 
thank you!

**Comment by gforsyth** [comment]
Thanks for the update, @snadukudy !  I've just rebased and updated this.  
@amoeba -- do you have a quick test you can run against pyarrow to confirm this works now?

**Comment by amoeba** [comment]
Hey @gforsyth, I tried and am still having an issue. May be user error though since it's been a while since I've done this. Can you check my steps?

1. Checked out this PR (`f94ecd58a2c1cf9bfbdc8c348dd3bcdabb432b92`), ran `poetry install`, `poetry shell`
2. Generated a plan from this Ibis code:
    ```python
    t = ibis.table([("a", "double")], name="table0")
    t.mutate(a=t["a"].floor())
    ```
3. Built pyarrow from recent main (`29553fd679ec3c114ae6e1eef8e279e55ce55a18`)
4. Ran the plan through Acero like
    ```python
    table_provider = ... # elided
    test_table_0 = pa.Table.from_pydict({"a": [1.1, 2.2, 3.3]})
    query_bytes = pa._substrait._parse_json_plan(query_json)
    result = pa.substrait.run_query(pa.py_buffer(query_bytes), table_provider=table_provider)
    print(result.read_all())
    ```

And I still get "Failed query query-0.json with exception: conversion to arrow::compute::Expression from Substrait expression cast {"

<details>
<summary>Full error output from pyarrow</summary>

```
Failed query query-0.json with exception: conversion to arrow::compute::Expression from Substrait expression cast {
  type {
    i64 {
      nullability: NULLABILITY_NULLABLE
    }
  }
  input {
    scalar_function {
      function_reference: 1
      output_type {
        i64 {
          nullability: NULLABILITY_NULLABLE
        }
      }
    }
  }
}

/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:549  FromProto(expr, ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/serde.cc:160  FromProto(plan_rel.has_root() ? plan_rel.root().input() : plan_rel.rel(), ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/serde.cc:202  DeserializePlans(buf, MakeNoSinkDeclarationFactory(), registry, ext_set_out, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/util.cc:49  DeserializePlan(substrait_buffer, registry, nullptr, conversion_options)
```
</details>

<details>
<summary>Substrait plan JSON</summary>

```json
{
  "extensionUris": [
    {
      "extensionUriAnchor": 1
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 1,
        "name": "floor"
      }
    }
  ],
  "relations": [
    {
      "root": {
        "input": {
          "project": {
            "common": {
              "emit": {
                "outputMapping": [
                  1
                ]
              }
            },
            "input": {
              "read": {
                "common": {
                  "direct": {}
                },
                "baseSchema": {
                  "names": [
                    "a"
                  ],
                  "struct": {
                    "types": [
                      {
                        "fp64": {
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      }
                    ],
                    "nullability": "NULLABILITY_REQUIRED"
                  }
                },
                "namedTable": {
                  "names": [
                    "table0"
                  ]
                }
              }
            },
            "expressions": [
              {
                "cast": {
                  "type": {
                    "i64": {
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "input": {
                    "scalarFunction": {
                      "functionReference": 1,
                      "outputType": {
                        "i64": {
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "names": [
          "a"
        ]
      }
    }
  ]
}
```
</details>

**Comment by westonpace** [comment]
That arrow commit (29553fd679ec3c114ae6e1eef8e279e55ce55a18) is not recent enough.  You want https://github.com/apache/arrow/commit/1c483e4196df3ad51c452ef13ac1ddf844b38193

**Comment by amoeba** [comment]
Thanks @westonpace. I now get this when I run that same substrait plan through Acero:

```
Failed query query-0.json with exception: substrait::Expression::Cast::FailureBehavior unspecified; must be FAILURE_BEHAVIOR_RETURN_NULL or FAILURE_BEHAVIOR_THROW_EXCEPTION
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/relation_internal.cc:549  FromProto(expr, ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/serde.cc:160  FromProto(plan_rel.has_root() ? plan_rel.root().input() : plan_rel.rel(), ext_set, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/serde.cc:202  DeserializePlans(buf, MakeNoSinkDeclarationFactory(), registry, ext_set_out, conversion_options)
/Users/bryce/src/apache/arrow/cpp/src/arrow/engine/substrait/util.cc:49  DeserializePlan(substrait_buffer, registry, nullptr, conversion_options)
```

**Comment by gforsyth** [comment]
Ok, that looks like ibis isn't specifying an option, I can take a look at that

**Comment by gforsyth** [comment]
ok @amoeba -- now we're specifying error behavior on `cast`, so this is ready for another try.

**Comment by amoeba** [comment]
`print(result.read_all())` gives me,

```
pyarrow.Table
cast(floor(FieldPath(0)), {to_type=int64, allow_int_overflow=false, allow_time_truncate=false, allow_time_overflow=false, allow_decimal_truncate=false, allow_float_truncate=false, allow_invalid_utf8=false}): int64
----
cast(floor(FieldPath(0)), {to_type=int64, allow_int_overflow=false, allow_time_truncate=false, allow_time_overflow=false, allow_decimal_truncate=false, allow_float_truncate=false, allow_invalid_utf8=false}): [[1,2,3]]
```

The type and the output looks good but the rest of the output looks like names aren't being managed correctly?

**Comment by thisisnic** [comment]
I'm not super familiar with ibis-substrait, so could be wrong, but I *think* what's happening here is that previously, [cast was originally implemented in ibis-substrait to use the cast function](https://github.com/substrait-io/substrait/issues/190#issuecomment-1125306949), which has [since been removed](https://github.com/substrait-io/substrait/blob/main/CHANGELOG.md#090-2022-07-31).  The cast implementation in Arrow expects the producer to use the cast expression instead.

Looking at the Substrait plan above, the `input` field in `cast` is a `scalarFunction`, whereas it's expecting a field reference expression (see https://github.com/substrait-io/substrait/blob/5788c1396c42e5f2326475a39f43598daa303325/site/docs/tutorial/final_plan.json for an example).

If that doesn't seem to be the case, let me know and I'll take a closer look at the Arrow cast implementation to see if something isn't quite right there.

**Comment by gforsyth** [comment]
@thisisnic -- the `input` field in a `Cast` is an `Expression`, so I think any Expression is valid (that's in this list): https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L566-L578

there may be _other_ issues with the plan we're creating, but I think that part is valid.

**Comment by thisisnic** [comment]
> @thisisnic -- the `input` field in a `Cast` is an `Expression`, so I think any Expression is valid (that's in this list): https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L566-L578
> 
> there may be _other_ issues with the plan we're creating, but I think that part is valid.

OK, thanks for clarifying that.

In Acero, the `input` field is deserialized and then passed into the Acero cast function.  The Acero cast function looks like it can either take an Array or an individual object of class Datum (so a scalar, array, etc).  I think these map nicely to literals and field references, but it's failing when a function is passed in as Acero doesn't know how to handle that input.

I've opened https://github.com/apache/arrow/issues/34365, & will continue the discussion there in terms of how to handle `ScalarFunction`s being passed in.

**Comment by westonpace** [comment]
> The type and the values look good but the rest of the output looks like names aren't being managed correctly?

Can you share the full plan?  Does the plan specify output names?

`cast(floor(FieldPath(0)), {to_type=int64, allow_int_overflow=false, allow_time_truncate=false, allow_time_overflow=false, allow_decimal_truncate=false, allow_float_truncate=false, allow_invalid_utf8=false})`

This is the name that Acero invents when no name is given to it.

**Comment by amoeba** [comment]
Full plan:

<details>
<summary>Substrait Plan as JSON</summary>

```json
{
  "extensionUris": [
    {
      "extensionUriAnchor": 1
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 1,
        "name": "floor"
      }
    }
  ],
  "relations": [
    {
      "root": {
        "input": {
          "project": {
            "common": {
              "emit": {
                "outputMapping": [
                  1
                ]
              }
            },
            "input": {
              "read": {
                "common": {
                  "direct": {}
                },
                "baseSchema": {
                  "names": [
                    "a"
                  ],
                  "struct": {
                    "types": [
                      {
                        "fp64": {
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      }
                    ],
                    "nullability": "NULLABILITY_REQUIRED"
                  }
                },
                "namedTable": {
                  "names": [
                    "table0"
                  ]
                }
              }
            },
            "expressions": [
              {
                "cast": {
                  "type": {
                    "i64": {
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "input": {
                    "scalarFunction": {
                      "functionReference": 1,
                      "outputType": {
                        "i64": {
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      },
                      "arguments": [
                        {
                          "value": {
                            "selection": {
                              "directReference": {
                                "structField": {}
                              },
                              "rootReference": {}
                            }
                          }
                        }
                      ]
                    }
                  },
                  "failureBehavior": "FAILURE_BEHAVIOR_THROW_EXCEPTION"
                }
              }
            ]
          }
        },
        "names": [
          "a"
        ]
      }
    }
  ]
}
```
</details>

**Comment by westonpace** [comment]
The Substrait plan included the column names.  It appears we've regressed in our ability to map these names in Acero (there was an outstanding issue to add a regression test here).  I believe this will be addressed by https://github.com/apache/arrow/pull/34406

**Comment by snadukudy** [comment]
> 

Thanks Weston. I see this is resolved now. @gforsyth, should we ask @amoeba to test again?

**Comment by gforsyth** [comment]
Sure.  I've run it on a recent commit of `pyarrow` but I'm not sure what exactly we're looking for (beyond the correct `floor` and `ceil` behavior)

**Comment by westonpace** [comment]
My understanding was that the output names were incorrect?

**Comment by amoeba** [comment]
Hey @gforsyth, I just ran my test again and the output looks right (names too). Running the same expression as above with the latest pyarrow.

This expression: 

```
arrow_table = pyarrow.Table.from_pydict({"a": [1.1, 2.2, 3.3]})
# ...magic to get turn into ibis Table
table.mutate(
    atimestwo=table.a * 2, 
    adotceil=table.a.ceil(), 
    adotfloor=table.a.floor()
)
```
Produces:

```
pyarrow.Table
a: double
atimestwo: double
adotceil: double
adotfloor: double
----
a: [[1.1,2.2,3.3]]
atimestwo: [[2.2,4.4,6.6]]
adotceil: [[2,3,4]]
adotfloor: [[1,2,3]]
```

<details>
<summary>Full output w/ plan JSON</summary>

```
>>> Printing Substrait plan as JSON...
{
  "extensionUris": [
    {
      "extensionUriAnchor": 1
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 1,
        "name": "multiply"
      }
    },
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 2,
        "name": "ceil"
      }
    },
    {
      "extensionFunction": {
        "extensionUriReference": 1,
        "functionAnchor": 3,
        "name": "floor"
      }
    }
  ],
  "relations": [
    {
      "root": {
        "input": {
          "project": {
            "common": {
              "emit": {
                "outputMapping": [
                  1,
                  2,
                  3,
                  4
                ]
              }
            },
            "input": {
              "read": {
                "common": {
                  "direct": {}
                },
                "baseSchema": {
                  "names": [
                    "a"
                  ],
                  "struct": {
                    "types": [
                      {
                        "fp64": {
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      }
                    ],
                    "nullability": "NULLABILITY_REQUIRED"
                  }
                },
                "namedTable": {
                  "names": [
                    "table0"
                  ]
                }
              }
            },
            "expressions": [
              {
                "selection": {
                  "directReference": {
                    "structField": {}
                  },
                  "rootReference": {}
                }
              },
              {
                "scalarFunction": {
                  "functionReference": 1,
                  "outputType": {
                    "fp64": {
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "arguments": [
                    {
                      "value": {
                        "selection": {
                          "directReference": {
                            "structField": {}
                          },
                          "rootReference": {}
                        }
                      }
                    },
                    {
                      "value": {
                        "literal": {
                          "i8": 2
                        }
                      }
                    }
                  ]
                }
              },
              {
                "scalarFunction": {
                  "functionReference": 2,
                  "outputType": {
                    "i64": {
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "arguments": [
                    {
                      "value": {
                        "selection": {
                          "directReference": {
                            "structField": {}
                          },
                          "rootReference": {}
                        }
                      }
                    }
                  ]
                }
              },
              {
                "scalarFunction": {
                  "functionReference": 3,
                  "outputType": {
                    "i64": {
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "arguments": [
                    {
                      "value": {
                        "selection": {
                          "directReference": {
                            "structField": {}
                          },
                          "rootReference": {}
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        "names": [
          "a",
          "atimestwo",
          "adotceil",
          "adotfloor"
        ]
      }
    }
  ]
}
>>> Calling read_all()...
pyarrow.Table
a: double
atimestwo: double
adotceil: double
adotfloor: double
----
a: [[1.1,2.2,3.3]]
atimestwo: [[2.2,4.4,6.6]]
adotceil: [[2,3,4]]
adotfloor: [[1,2,3]]
```

**Comment by gforsyth** [comment]
woohoo!  Thanks @amoeba.  Merging this in. then.

**Pull request merged**
